### ISSUE TITLE
Failed Common.xpath_exists? on Android 9.0 while checking the availability of document content

### ISSUE THREAD

**Issue by kayner** [kayner/Onlyoffice-android-opener#1]
The problem may be caused by frequent calls to the element's xpath.
```
Feature: Opening files in a folder and creating screenshots for each
  Opening files with extensions .docx, .xlsx, .pptx and creating a screenshot showing the contents of the file.

  Background: Sign in to portal             # features/opener.feature:5
    When Skip Onboarding Panel              # features/step_definitions/opener.rb:1
    Then Enter portal domain-name in field  # features/step_definitions/opener.rb:5
    And Tap on the button Next              # features/step_definitions/opener.rb:10
    Then Enter the account email in field   # features/step_definitions/opener.rb:15
    And Enter the account password in field # features/step_definitions/opener.rb:20
    And Tap on the button Sign In           # features/step_definitions/opener.rb:25

  Scenario: Open files and take screenshots # features/opener.feature:13
    Then Open the first folder in list      # features/step_definitions/opener.rb:30
    And Open each file and take screenshot  # features/step_definitions/opener.rb:35
      UiSelector[INSTANCE=0, RESOURCE_ID=com.onlyoffice.documents:id/list_of_items] (Selenium::WebDriver::Error::NoSuchElementError)
      NoSuchElementError: UiSelector[INSTANCE=0, RESOURCE_ID=com.onlyoffice.documents:id/list_of_items]
          at errorFromMJSONWPStatusCode (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:786:12)
          at Socket.socketClient.on.data (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\bootstrap.js:139:18)
          at Socket.emit (events.js:182:13)
          at addChunk (_stream_readable.js:279:12)
          at readableAddChunk (_stream_readable.js:260:13)
          at Socket.Readable.push (_stream_readable.js:219:10)
          at TCP.onread (net.js:636:20)
      ./features/support/document_list.rb:29:in `width'
      ./features/support/document_list.rb:41:in `swipe_up'
      ./features/step_definitions/opener.rb:45:in `block (3 levels) in <top (required)>'
      ./features/step_definitions/opener.rb:43:in `loop'
      ./features/step_definitions/opener.rb:43:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/opener.rb:39:in `loop'
      ./features/step_definitions/opener.rb:39:in `/^Open each file and take screenshot$/'
      features/opener.feature:15:in `And Open each file and take screenshot'

Failing Scenarios:
cucumber features/opener.feature:13 # Scenario: Open files and take screenshots

1 scenario (1 failed)
8 steps (1 failed, 7 passed)
1m48.412s

```

**Comment by kayner** [comment]
Set UiAutomator2 for default appium driver in env.rb
